version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest-asyncio
    versions:
    - 0.14.0
    - 0.15.0
  - dependency-name: pytest
    versions:
    - 6.2.2
